### ISSUE TITLE
Location-based recommendations

### ISSUE THREAD

**Issue by sathvikn** [bailfunds/bailfunds.github.io#16]
If people's IP addresses are traceable, could we implement an alert that shows their local bail fund?

**Comment by goldenercobra** [comment]
Hi there,

Out of concern for privacy, we are not tracking any IP addresses (we disabled all forms of analytics). And if we were, Jekyll are static-pages which means JS sorting is out of scope.

**Comment by sathvikn** [comment]
Great that you're not tracking IP addresses, I haven't done too much modern web dev so wasn't sure about the implementational details. Thanks!

**Comment by andyzwang** [comment]
Just for sake's of transparency: we've added analytics, but have all IP's are anonymized as soon as they reach the server (last bits of the IP all are written as 0's).
