### ISSUE TITLE
frequency of AB page updates?

### ISSUE THREAD

**Issue by MetricMike** [bailfunds/bailfunds.github.io#21]
Does the https://secure.actblue.com/donate/bailfundscovid page update frequently in response to funds asking for donations to be directed elsewhere? E.g., Brooklyn Bail Fund has asked donations to go elsewhere, and that's annotated on bailfunds.github.io - if I donate today through AB, will part of my donation go to BBF?

**Comment by andyzwang** [comment]
Hi MetricMike,

Although we've worked closely with the NBFN, we're unaffiliated with them -- to that end, I don't know how their ActBlue page works. I'd suggest dropping them a line on their website or checking their Twitter. 

Sorry I don't have a clearer answer!
